=== matelat-daw/htdocs/Examen-LND/DTD/aeropuertos.dtd
<!ELEMENT aeropuertos (aeropuerto*)>
<!ELEMENT aeropuerto (nombre, vuelos, fecha)>
<!ELEMENT vuelos (vuelo*)>
<!ELEMENT vuelo (diario?, origen, destino, hora-salida, hora-llegada)>
<!ELEMENT diario EMPTY>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora-salida (#PCDATA)>
<!ELEMENT hora-llegada (#PCDATA)>
<!ATTLIST vuelo cÃ³digo ID #REQUIRED
                estado CDATA "E">

=== matelat-daw/htdocs/Examen-LND/18 - César Matelat/vuelos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aeropuertos SYSTEM "DTD/aeropuertos.dtd">

<aeropuertos>
  <aeropuerto>
    <nombre>JFK</nombre>
    <vuelos>
      <vuelo código="V22" estado="C">
         <diario />
         <origen>New York</origen>
         <destino>Chicago</destino>
         <hora-salida>09:30:00</hora-salida>
         <hora-llegada>11:30:00</hora-llegada>
      </vuelo>
      <vuelo código="V23" estado="R">
         <origen>New York</origen>
         <destino>Miami</destino>
         <hora-salida>10:15:00</hora-salida>
         <hora-llegada>11:15:00</hora-llegada>
      </vuelo>
      <vuelo código="V24" estado="">
         <origen>New York</origen>
         <destino>Montreal</destino>
         <hora-salida>17:34:00</hora-salida>
         <hora-llegada>19:15:00</hora-llegada>
      </vuelo>
   </vuelos>
   <fecha>2023-10-10</fecha>
  </aeropuerto>
  <aeropuerto>
   <nombre>Adolfo Suárez</nombre>
   <vuelos>
     <vuelo código="X34" estado="">
        <origen>Madrid</origen>
        <destino>New York</destino>
        <hora-salida>10:00:00</hora-salida>
        <hora-llegada>12:10:00</hora-llegada>
     </vuelo>
  </vuelos>
  <fecha>2023-10-20</fecha>
 </aeropuerto>
</aeropuertos>
