<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Catalogo [
  <!ELEMENT Catalogo (Ordenadores, Consolas, TV)>
  <!ELEMENT Ordenadores (Portatil, PC)>
  <!ELEMENT Consolas (Consola)>
  <!ELEMENT Consola (name, desc?, price, Caracteristicas)?>
  <!ELEMENT Portatil (name, desc, price, Caracteristicas)?>
  <!ELEMENT PC (name, desc, price, Caracteristicas)?>
  <!ELEMENT TV (name, desc, price, Caracteristicas)?>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT desc (#PCDATA)>
  <!ELEMENT price (#PCDATA)>
  <!ELEMENT Caracteristicas (caracteristica*)>
  <!ELEMENT caracteristica (#PCDATA)>
  <!ATTLIST caracteristica name NMTOKEN #REQUIRED>

]>

<Catalogo>
    <Ordenadores>
        <Portatil>
            <name>HP Pavilion</name>
            <desc>Potente Portátil de 17" Resolución HD 1080</desc>
            <price>1500 €</price>
            <Caracteristicas>
                <caracteristica name="cpu">Core i7 13400</caracteristica>
                <caracteristica name="memory">16 GBytes 2400 MHz.</caracteristica>
                <caracteristica name="ssd">NVE M2 1 Tera</caracteristica>
            </Caracteristicas>
        </Portatil>
        <PC/>
    </Ordenadores>
    <Consolas>
        <Consola>
            <name>Play Station 6</name>
            <price>750 €</price>
            <Caracteristicas>
                <caracteristica name="cpu">Sony 38000</caracteristica>
                <caracteristica name="memory">16 GBytes 2400 MHz.</caracteristica>
                <caracteristica name="ssd">NVE M2 1 Tera</caracteristica>
            </Caracteristicas>
        </Consola>
    </Consolas>
    <TV/>
</Catalogo>