=== matelat-daw/htdocs/Examen-LND/18 - César Matelat/DTD/facturas.dtd
<!ELEMENT facturas (factura*)>
<!ELEMENT factura (datos-emisor, datos-cliente, detalle-factura)*>
<!ELEMENT datos-emisor (nombre, cif, teléfono?)>
<!ELEMENT datos-cliente (nombre, cif, teléfono+)>
<!ELEMENT detalle-factura (línea+)>
<!ELEMENT línea (descripción, cantidad, oferta?, pvp)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT teléfono (#PCDATA)>
<!ELEMENT descripción (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT oferta EMPTY>
<!ELEMENT pvp (#PCDATA)>
<!ATTLIST factura número ID #REQUIRED
                  fecha CDATA #REQUIRED
                  moneda CDATA "euro">
<!ATTLIST detalle-factura importe CDATA #REQUIRED>
<!ATTLIST línea código-artículo CDATA #REQUIRED
                tipo CDATA "DVD">

=== matelat-daw/htdocs/Examen-LND/18 - César Matelat/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "DTD/facturas.dtd">

<facturas>
<factura número="Fact-27" fecha="2013-12-18" moneda="Euro" >
   <datos-emisor>
      <nombre>Librería Pérez</nombre>
      <cif>44555666-B</cif>
      <teléfono>777888999</teléfono>
   </datos-emisor>
   <datos-cliente>
      <nombre>Biblioteca Txantrea</nombre>
      <cif>33111222-A</cif>
      <teléfono>333999444</teléfono>
   </datos-cliente>
   <detalle-factura importe="86.12">
      <línea código-artículo="AW7" tipo="Libro">
         <descripción>Analítica Web 2.0</descripción>
         <cantidad>1</cantidad>
         <oferta />
         <pvp>25.12</pvp>
      </línea>
      <línea código-artículo="CP5" tipo="DVD">
         <descripción>Curso de HTML</descripción>
         <cantidad>2</cantidad>
         <pvp>30.5</pvp>
      </línea>
   </detalle-factura>
</factura>
<factura número="Fact-28" fecha="2023-05-10" moneda="Euro" >
   <datos-emisor>
      <nombre>PC Componentes</nombre>
      <cif>N4528283-B</cif>
      <teléfono>931123456</teléfono>
   </datos-emisor>
   <datos-cliente>
      <nombre>César Matelat</nombre>
      <cif>42268151-Q</cif>
      <teléfono>664774821</teléfono>
   </datos-cliente>
   <detalle-factura importe="145.75">
      <línea código-artículo="SSD 1TB Kingston a400" tipo="Varios">
         <descripción>Dispositivo de Estado Sólido para Almacenamiento</descripción>
         <cantidad>1</cantidad>
         <oferta />
         <pvp>65.25</pvp>
      </línea>
      <línea código-artículo="Windows 11" tipo="DVD">
         <descripción>Sistema Operativo Windows 11</descripción>
         <cantidad>1</cantidad>
         <pvp>80.50</pvp>
      </línea>
   </detalle-factura>
</factura>
</facturas>
