=== matelat-daw/htdocs/XML/DTD/DTD/DTD/albumes.dtd
<!ELEMENT Albumes (Album*)>
<!ELEMENT Album (ID, Foto)*>
<!ELEMENT Foto (place, date, camera, people, modelo)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT camera (#PCDATA)>
<!ELEMENT people (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>

=== matelat-daw/htdocs/XML/DTD/DTD/EXT-Albumes-Ej-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Albumes SYSTEM "DTD/albumes.dtd">

<Albumes>
    <Album>
        <ID>1</ID>
        <Foto>
            <place>Mar del Plata</place>
            <date>12/04/1968</date>
            <camera>Zeiss Icon</camera>
            <people>Me</people>
            <monument>Torreón del Monje</monument>
        </Foto>
        <ID>2</ID>
        <Foto>
            <place>Tenerife</place>
            <date>07-09-2002</date>
            <camera>Cannon</camera>
            <people>Me</people>
            <monument>Cima de El Teide</monument>
        </Foto>
        <ID>3</ID>
        <Foto>
            <place>La Palma</place>
            <date>15-04-2005</date>
            <camera>Sony</camera>
            <people>Me</people>
            <monument>El Roque de Los Muchachos</monument>
        </Foto>
    </Album>
    <Album>
        <ID>1</ID>
        <Foto>
            <place>Mar del Plata</place>
            <date>01-09-2007</date>
            <camera>Samsung</camera>
            <people>Me</people>
            <monument>Playa La Perla</monument>
        </Foto>
        <ID>2</ID>
        <Foto>
            <place>Barcelona</place>
            <date>01-07-2007</date>
            <camera>Samsung</camera>
            <people>Me</people>
            <monument>El Mont Juic</monument>
        </Foto>
        <ID>3</ID>
        <Foto>
            <place>País Vasco</place>
            <date>05-01-2012</date>
            <camera>Sony</camera>
            <people>Me</people>
            <monument>Barakaldo</monument>
        </Foto>
    </Album>
</Albumes>

=== matelat-daw/htdocs/XML/DTD/DTD/Albumes-Ej-5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Albumes SYSTEM "DTD/albumes.dtd">

<Albumes>
    <Album>
        <ID>1</ID>
        <Foto>
            <place>Mar del Plata</place>
            <date>12/04/1968</date>
            <camera>Zeiss Icon</camera>
            <people>Me</people>
            <modelo>Antique Camera</modelo>
        </Foto>
        <ID>2</ID>
        <Foto>
            <place>Tenerife</place>
            <date>07-09-2002</date>
            <camera>Cannon</camera>
            <people>Me</people>
            <modelo>EOS 90D</modelo>
        </Foto>
        <ID>3</ID>
        <Foto>
            <place>La Palma</place>
            <date>15-04-2005</date>
            <camera>Sony</camera>
            <people>Me</people>
            <modelo>Telephone</modelo>
        </Foto>
    </Album>
    <Album>
        <ID>1</ID>
        <Foto>
            <place>Mar del Plata</place>
            <date>01-09-2007</date>
            <camera>Samsung</camera>
            <people>Me</people>
            <modelo>Telephone</modelo>
        </Foto>
        <ID>2</ID>
        <Foto>
            <place>Barcelona</place>
            <date>01-07-2007</date>
            <camera>Samsung</camera>
            <people>Me</people>
            <modelo>Telephone</modelo>
        </Foto>
        <ID>3</ID>
        <Foto>
            <place>Pa√≠s Vasco</place>
            <date>05-01-2012</date>
            <camera>Sony</camera>
            <people>Me</people>
            <modelo>Telephone</modelo>
        </Foto>
    </Album>
</Albumes>
