=== matelat-daw/htdocs/XML/DTD/DTD/DTD/empresa.dtd
<!ELEMENT Empresa (Empleado*)>
<!ELEMENT Empleado (name, surname1, surname2, yearsold, department, position)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname1 (#PCDATA)>
<!ELEMENT surname2 (#PCDATA)>
<!ELEMENT yearsold (#PCDATA)>
<!ELEMENT department (#PCDATA)>
<!ELEMENT position (#PCDATA)>

=== matelat-daw/htdocs/XML/DTD/DTD/EXT-Empresa-Ej-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Empresa SYSTEM "DTD/empresa.dtd">

<Empresa>
    <Empleado>
        <name>Ana</name>
        <surname1>García</surname1>
        <surname2></surname2>
        <yearsold>30</yearsold>
        <department>Ventas</department>
        <position>Ejecutiva de Ventas</position>
    </Empleado>
    <Empleado>
        <name>Luis</name>
        <surname1>Rodríguez</surname1>
        <surname2></surname2>
        <yearsold>45</yearsold>
        <department>Finanzas</department>
        <position>Analista Financiero</position>
    </Empleado>
    <Empleado>
        <name>María</name>
        <surname1>López</surname1>
        <surname2></surname2>
        <yearsold>28</yearsold>
        <department>Marketing</department>
        <position>Especialista en Redes Sociales</position>
    </Empleado>
</Empresa>
