<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Personas [
  <!ELEMENT Personas (Persona*)>
  <!ELEMENT Persona (nombre+, nacimiento?, direccion+, genero)> <!-- Con ? puede o no aparecer. -->
  <!ELEMENT direccion (calle, poblacion, provincia, cpostal)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT nacimiento EMPTY>
  <!ELEMENT calle (#PCDATA)>
  <!ELEMENT poblacion (#PCDATA)>
  <!ELEMENT provincia (#PCDATA)>
  <!ELEMENT cpostal (#PCDATA)>
  <!ELEMENT genero (#PCDATA)>
  <!ATTLIST nacimiento day CDATA #REQUIRED
                        month CDATA #REQUIRED
                        year CDATA #REQUIRED>
]>

<Personas>
    <Persona>
        <nombre>María Pía</nombre>
        <direccion>
            <calle>Herradores 1</calle>
            <poblacion>San Cristóbal de La Laguna</poblacion>
            <provincia>Tenerife</provincia>
            <cpostal>38201</cpostal>
        </direccion>
        <genero>Mujer</genero>
    </Persona>
    <Persona>
        <nombre>Juan Pérez</nombre>
        <direccion>
            <calle>Serrano S/N</calle>
            <poblacion>Madrid</poblacion>
            <provincia>Madrid</provincia>
            <cpostal>28001</cpostal>
        </direccion>
        <genero>Varón</genero>
    </Persona>
    <Persona>
        <nombre>César Matelat</nombre>
        <nacimiento day="5" month="Abril" year="1968"/>
        <direccion>
            <calle>Fermín Morín X</calle>
            <poblacion>Santa Cruz de Tenerife</poblacion>
            <provincia>Tenerife</provincia>
            <cpostal>38007</cpostal>
        </direccion>
        <genero>Varón</genero>
    </Persona>
</Personas>